### ISSUE TITLE
Step to install build

### ISSUE THREAD

**Issue by waynelen6** [isabolic/apex-chat-region#1]
Hai sir, 
I loving this features. Could you please explain more details in how to install build.
Thank You

Regards
Wayne Len

**Comment by isabolic** [comment]
Hi @waynelen6 have you checked README.md there is paragraph **"Install build version"** and **"How to"**..

**Comment by waynelen6** [comment]
Hai @isabolic,
I have been follow each step on README.md
Everything look right, but end up chat still not working. You may have a look on following print scree
https://www.dropbox.com/s/hffdoo8ojxulln6/Untitled.png?dl=0
May I know how to identify the problem? 

Thank You
Regards
Wayne Len

**Comment by isabolic** [comment]
Hi @waynelen6,

my guess is that client ( for example you machine ) can't resolve hostname **wyi.maxapex.net** 
1) try from you cmd ping **wyi.maxapex.net** if you get host is unreachable then that is your problem, then try ip address of the same machine
2) for more details please attach sreenshoot of network (in browser -> developer tools -> network -> WS)
   you can read how to do that  [here](https://dev.to/isabolic99/oracle-apex-chat-demo) check **paragraph =>  _Monitoring network between client and server_**

**Comment by waynelen6** [comment]
Hi @isabolic 

1. host name is wyl.maxapex.net instead of wyi, its able to ping
2. nothing shown on WS (pls refer [here](https://www.dropbox.com/s/7xvhbv8w8ugs8jv/2.png?dl=0) )

**Comment by isabolic** [comment]
@waynelen6 

I sea that hostname is reachable, that is good, but i see some error in console (in browser -> developer tools - > console)
can you please attach **console** screenshot?

tnx

**Comment by waynelen6** [comment]
@isabolic 

Please refer [here](https://www.dropbox.com/s/gi2l3d2itqqoa6n/3.png?dl=0).

Thank you

**Comment by isabolic** [comment]
@waynelen6 

from console I can see node.server is not responsding.
Try this steps:

1) In cmd exit node.js, terminate program
2) in package.json there is property called **server** and for value set ip address instead of hostname
3) run **node.js chat.js &** (this & simbol is also required, it tells node to run process async )
4) in apex plugin **socket server** change hostname with ip address

when you done that plese attach screenshot from console and WS

Best regards
isabolic

**Comment by isabolic** [comment]
@waynelen6 is the issue still present?

**Comment by waynelen6** [comment]
@isabolic I get back to u by tomorrow, its Malaysia supper time now. Thank again for ur help.

**Comment by waynelen6** [comment]
Hai @isabolic ,

Here is the latest error came from developer tools [here ](https://www.dropbox.com/s/gi2l3d2itqqoa6n/3.png?dl=0)

**Comment by isabolic** [comment]
@waynelen6 
1) from console I can see node.server is still not responding and there reason is that you run apex on https. 
When you run application on https all web resources also must go through https. Currently I'm not supporting https. (on node is needed to be set certificate ) Can you run you application on **http** for now?

2) regarding the second issue **Cannot read property 'replace' of null**, i have fixed it now. So to apply you need to install **from build** new version of plugin region_type_plugin_apex_socket_chat_room.sql into your application

3) Can you tell me **authentication scheme type** do you use (for login)?

**Comment by isabolic** [comment]
created **feature request** (issue) for [https](https://github.com/isabolic/apex-chat-region/issues/3)

**Comment by waynelen6** [comment]
@isabolic 

2 ) I tried to install from build new version of plugin having following error:
Invalid Plug-in File : File is not a valid Application Express plug-in export file.

3) I using custom authentication on my application, but for this plugin chat page I open to public.

**Comment by isabolic** [comment]
@waynelen6 

2) can you please attach file that you used for install in dropbox and attach link here, also witch version of apex do you use?

3) Can you tell me then if plugin is asking you for chatname, like in apex demo that I post?
