### ISSUE TITLE
Cannot Get/

### ISSUE THREAD

**Issue by HADAET** [isabolic/apex-chat-region#12]
npm WARN apex.chat.module@1.0.0 No description
npm WARN apex.chat.module@1.0.0 No repository field.

**Comment by isabolic** [comment]
HI @HADAET 

can you please attach a screenshot of directory and error that you get from CLI.

**Comment by HADAET** [comment]
This screenshot of directory
![image](https://user-images.githubusercontent.com/39644584/40596169-f5192052-625a-11e8-9aec-fabb2dd6de46.png)

**Comment by isabolic** [comment]
Hi @HADAET I can't see the issue you have. Your title for the issue is "Cannot Get/" and description "npm WARN ..." but from CLI screenshot everything is fine. Can you be more specific?

**Comment by isabolic** [comment]
no replay from user, closing issue
