### ISSUE TITLE
messages (shared components) install script

### ISSUE THREAD

**Issue by isabolic** [isabolic/apex-chat-region#8]
find a way to create (single) install script for messages/shared components, messages can cannot be imported in outher apex parsing schema because of this: 
begin
wwv_flow_api.import_begin (
 p_version_yyyy_mm_dd=>'2013.01.01'
,p_release=>'5.0.2.00.07'
,p_default_workspace_id=>999999
,p_default_application_id=>100
,p_default_owner=>'PLAYGROUND'
);
end;
/

**Comment by RAZAA12** [comment]
Please, can you paste a youtube link here that how this works???????? please

**Comment by RAZAA12** [comment]
It's urgent as well

**Comment by RAZAA12** [comment]
and provide a complete description that how it can be made usable on oracle apex 5.1

**Comment by isabolic** [comment]
please read the manual, it's step by step guide

**Comment by RAZAA12** [comment]
I have done the same way but I am unable to understand what does mean by server port and IP ??? please guide me, I am beginner

**Comment by RAZAA12** [comment]
how to compile it on apex parsing schema and following the steps chat.js& cannot be compiled, why????

**Comment by RAZAA12** [comment]
when I run the node chat.js & , I find module.js:544 throw error, whats this???

module.js:544
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at C:\node.server\chat.js:12:21
    at Object.<anonymous> (C:\node.server\chat.js:205:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12),
this is problem

**Comment by isabolic** [comment]
1) ip address -> https://en.wikipedia.org/wiki/IP_address     
2) server name -> https://en.wikipedia.org/wiki/Name_server
3) compile apex parshing objects (pack specs and body in oracle db, apex parshing schema) https://github.com/isabolic/apex-chat-region/tree/master/packages
  then import the apex plugin from apex builder
   https://github.com/isabolic/apex-chat-region/blob/master/region_type_plugin_apex_socket_chat_room.sql
4) in terminal first you run 
   - npm install  
   - set servername or ip address in package.json
   - npm chat.js&

based on your comments i can tell that you are not the IT guy, so my advice is that you give this task someone how is.
